//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineQuranServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Enrollments = new HashSet<Enrollment>();
            this.QuranLessons = new HashSet<QuranLesson>();
            this.TeacherCourses = new HashSet<TeacherCourse>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string Sub_title { get; set; }
    
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual ICollection<QuranLesson> QuranLessons { get; set; }
        public virtual ICollection<TeacherCourse> TeacherCourses { get; set; }
    }
}
