//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineQuranServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseProgressLog
    {
        public CourseProgressLog()
        {
            this.TeacherRatings = new HashSet<TeacherRating>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> CallStartTime { get; set; }
        public Nullable<System.DateTime> CallEndTime { get; set; }
        public string Status { get; set; }
        public Nullable<int> EnrollmentSlot_Id { get; set; }
        public Nullable<int> AyatPointerId { get; set; }
        public Nullable<int> QuranLesson_id { get; set; }
    
        public virtual EnrollmentSlot EnrollmentSlot { get; set; }
        public virtual QuranLesson QuranLesson { get; set; }
        public virtual ICollection<TeacherRating> TeacherRatings { get; set; }
    }
}
