//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineQuranServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentSlot
    {
        public EnrollmentSlot()
        {
            this.CourseProgressLogs = new HashSet<CourseProgressLog>();
        }

        public EnrollmentSlot(int enroll_id, int slot_id)
        {
            this.slot_id = slot_id;
        }

        public int id { get; set; }
        public int enrollment_id { get; set; }
        public int slot_id { get; set; }
    
        public virtual ICollection<CourseProgressLog> CourseProgressLogs { get; set; }
        public virtual Enrollment Enrollment { get; set; }
        public virtual Slot Slot { get; set; }
    }
}
