//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineQuranServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public Enrollment()
        {
            this.EnrollmentSlots = new HashSet<EnrollmentSlot>();
        }

        public Enrollment(int student_id, int teacher_id, int course_id, DateTime dateTime, object value, bool v)
        {
            this.student_id = student_id;
            this.teacher_id = teacher_id;
            this.course_id = course_id;
        }

        public int id { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> teacher_id { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> finish_date { get; set; }
        public Nullable<bool> completed { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<EnrollmentSlot> EnrollmentSlots { get; set; }
    }
}
