//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineQuranServer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QURAN_TUTOR_DBEntities3 : DbContext
    {
        public QURAN_TUTOR_DBEntities3()
            : base("name=QURAN_TUTOR_DBEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Course> Courses { get; set; }
        public DbSet<CourseProgressLog> CourseProgressLogs { get; set; }
        public DbSet<Enrollment> Enrollments { get; set; }
        public DbSet<EnrollmentSlot> EnrollmentSlots { get; set; }
        public DbSet<Parent> Parents { get; set; }
        public DbSet<Quran> Qurans { get; set; }
        public DbSet<QuranLesson> QuranLessons { get; set; }
        public DbSet<Ruku> Rukus { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<Surah> Surahs { get; set; }
        public DbSet<Teacher> Teachers { get; set; }
        public DbSet<TeacherRating> TeacherRatings { get; set; }
        public DbSet<TeacherCourse> TeacherCourses { get; set; }
        public DbSet<Slot> Slots { get; set; }
    }
}
