//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineQuranServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuranLesson
    {
        public QuranLesson()
        {
            this.CourseProgressLogs = new HashSet<CourseProgressLog>();
        }
    
        public int id { get; set; }
        public Nullable<int> SurahNo { get; set; }
        public Nullable<int> ruku_id { get; set; }
        public Nullable<int> course_id { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<CourseProgressLog> CourseProgressLogs { get; set; }
        public virtual Ruku Ruku { get; set; }
    }
}
