//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineQuranServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quran
    {
        public int id { get; set; }
        public int surah_id { get; set; }
        public short Ayah_id { get; set; }
        public string AyahText { get; set; }
        public Nullable<int> Ruku_id { get; set; }
    
        public virtual Ruku Ruku { get; set; }
        public virtual Surah Surah { get; set; }
    }
}
