//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineQuranServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruku
    {
        public Ruku()
        {
            this.Qurans = new HashSet<Quran>();
            this.QuranLessons = new HashSet<QuranLesson>();
        }
    
        public int id { get; set; }
        public int SurahNo { get; set; }
        public int RukuNo { get; set; }
        public int StartingAyahNo { get; set; }
        public int EndingAyahNo { get; set; }
    
        public virtual ICollection<Quran> Qurans { get; set; }
        public virtual ICollection<QuranLesson> QuranLessons { get; set; }
    }
}
