//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineQuranServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slot
    {
        public Slot()
        {
            this.EnrollmentSlots = new HashSet<EnrollmentSlot>();
        }
    
        public int id { get; set; }
        public Nullable<System.TimeSpan> from_time { get; set; }
        public Nullable<System.TimeSpan> to_time { get; set; }
        public Nullable<int> teacher_id { get; set; }
        public string Day { get; set; }
        public Nullable<bool> IsBusy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<EnrollmentSlot> EnrollmentSlots { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
