//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineQuranServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surah
    {
        public Surah()
        {
            this.Qurans = new HashSet<Quran>();
        }
    
        public int id { get; set; }
        public string SurahName { get; set; }
    
        public virtual ICollection<Quran> Qurans { get; set; }
    }
}
