//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineQuranServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Enrollments = new HashSet<Enrollment>();
            this.TeacherCourses = new HashSet<TeacherCourse>();
            this.Slots = new HashSet<Slot>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string cnic { get; set; }
        public string region { get; set; }
        public string qualification { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string pic { get; set; }
        public Nullable<int> ratings { get; set; }
        public Nullable<int> hourly_rate { get; set; }
        public string SampleClip { get; set; }
        public Nullable<int> TimeZone { get; set; }
    
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual ICollection<TeacherCourse> TeacherCourses { get; set; }
        public virtual ICollection<Slot> Slots { get; set; }
    }
}
