//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineQuranServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherRating
    {
        public int id { get; set; }
        public int courseProgressLog_id { get; set; }
        public int RatingValue { get; set; }
        public Nullable<System.DateTime> RatedAt { get; set; }
        public Nullable<bool> IsParent { get; set; }
    
        public virtual CourseProgressLog CourseProgressLog { get; set; }
    }
}
